### PR TITLE
add record bat and update md

### PR DESCRIPTION
**Pull request by NormanMises**

### CODE REVIEW

**Comment by odnar-dev** [comment]
thanks for the pr, 
- i didn't test the plugins for now, but it looks promising 
- this repo focus on streamlink plugins and not a live/cam recorder , please remove /recorder/

**Comment by NormanMises** [comment]
alright

**Comment by odnar-dev** [comment]
why the fuck did you close it ??

**Comment by NormanMises** [comment]
Sorry, I just wanted to add a recorder, the other plugins were copied from another repository🤣

**Pull request closed without merging**
